    ft_sharedptr<ft_building_definition> conveyor(new ft_building_definition());
    conveyor->id = BUILDING_CONVEYOR;
    conveyor->name = ft_string("Conveyor Belt");
    conveyor->width = 1;
    conveyor->height = 1;
    conveyor->logistic_cost = 0;
    conveyor->logistic_gain = 1;
    conveyor->energy_cost = 0.0;
    conveyor->energy_gain = 0.0;
    conveyor->cycle_time = 0.0;
    conveyor->inputs.clear();
    conveyor->outputs.clear();
    conveyor->build_costs.clear();
    recipe.key = ORE_IRON;
    recipe.value = 4;
    conveyor->build_costs.push_back(recipe);
    conveyor->mine_bonus = 0.0;
    conveyor->unique = false;
    conveyor->occupies_grid = true;
    conveyor->removable = true;
    this->register_definition(conveyor);

    ft_sharedptr<ft_building_definition> transfer(new ft_building_definition());
    transfer->id = BUILDING_TRANSFER_NODE;
    transfer->name = ft_string("Resource Transfer Node");
    transfer->width = 1;
    transfer->height = 1;
    transfer->logistic_cost = 0;
    transfer->logistic_gain = 2;
    transfer->energy_cost = 0.0;
    transfer->energy_gain = 0.0;
    transfer->cycle_time = 0.0;
    transfer->inputs.clear();
    transfer->outputs.clear();
    transfer->build_costs.clear();
    recipe.key = ORE_IRON;
    recipe.value = 6;
    transfer->build_costs.push_back(recipe);
    recipe.key = ORE_COPPER;
    recipe.value = 4;
    transfer->build_costs.push_back(recipe);
    transfer->mine_bonus = 0.0;
    transfer->unique = false;
    transfer->occupies_grid = true;
    transfer->removable = true;
    this->register_definition(transfer);

    ft_sharedptr<ft_building_definition> relay(new ft_building_definition());
    relay->id = BUILDING_TRADE_RELAY;
    relay->name = ft_string("Trade Relay Nexus");
    relay->width = 2;
    relay->height = 2;
    relay->logistic_cost = 1;
    relay->logistic_gain = 0;
    relay->energy_cost = 3.5;
    relay->energy_gain = 0.0;
    relay->cycle_time = 0.0;
    relay->inputs.clear();
    relay->outputs.clear();
    relay->build_costs.clear();
    recipe.key = ITEM_COPPER_BAR;
    recipe.value = 10;
    relay->build_costs.push_back(recipe);
    recipe.key = ITEM_ADVANCED_ENGINE_PART;
    recipe.value = 3;
    relay->build_costs.push_back(recipe);
    recipe.key = ITEM_ACCUMULATOR;
    recipe.value = 2;
    relay->build_costs.push_back(recipe);
    relay->mine_bonus = 0.0;
    relay->convoy_speed_bonus = 0.12;
    relay->convoy_raid_risk_modifier = 0.18;
    relay->unique = false;
    relay->occupies_grid = true;
    relay->removable = true;
    this->register_definition(relay);
