#include "game.hpp"
#include "libft/Libft/libft.hpp"
#include "libft/Template/pair.hpp"
#include "libft/Template/set.hpp"
#include "libft/Math/math.hpp"
#include "ft_map_snapshot.hpp"
#include "libft_math_bridge.hpp"

// Aggregated from refactored implementation slices
#include "game_lore_and_setup.cpp"
#include "game_production_and_combat.cpp"
#include "game_tick_and_accessors.cpp"
#include "game_state_configuration.cpp"
#include "game_achievements_and_buildings.cpp"
#include "game_planet_state.cpp"
#include "game_campaign_checkpoints.cpp"
#include "game_campaign_loading.cpp"
