#include "game.hpp"
#include "libft/Libft/libft.hpp"
#include "libft/Template/move.hpp"
#include "libft/Template/pair.hpp"
#include "ft_map_snapshot.hpp"

#include "game_quests_internal.cpp"
#include "game_quests_context.cpp"
#include "game_quests_completion.cpp"
#include "game_quests_failure.cpp"
#include "game_quests_choices.cpp"
#include "game_quests_accessors.cpp"
#include "game_quests_lore.cpp"
#include "game_quests_snapshot.cpp"
#include "game_backend_status.cpp"
