struct MainMenuPalette
{
    SDL_Color background;
    SDL_Color title;
    SDL_Color profile;
    SDL_Color button_idle;
    SDL_Color button_hover;
    SDL_Color button_selected;
    SDL_Color button_disabled;
    SDL_Color button_disabled_hover;
    SDL_Color button_border_enabled;
    SDL_Color button_border_disabled;
    SDL_Color button_text_enabled;
    SDL_Color button_text_disabled;
    SDL_Color description;
    SDL_Color hint;
    SDL_Color build;
    SDL_Color alert_text_error;
    SDL_Color alert_text_info;
    SDL_Color alert_background_error;
    SDL_Color alert_border_error;
    SDL_Color alert_background_info;
    SDL_Color alert_border_info;
    SDL_Color overlay_heading;
    SDL_Color overlay_line;
    SDL_Color overlay_footer;
    SDL_Color overlay_background;
    SDL_Color overlay_border;
    SDL_Color tutorial_title;
    SDL_Color tutorial_primary;
    SDL_Color tutorial_secondary;
    SDL_Color tutorial_background;
    SDL_Color tutorial_border;
    SDL_Color autosave_icon_idle;
    SDL_Color autosave_icon_in_progress;
    SDL_Color autosave_icon_success;
    SDL_Color autosave_icon_failure;
    SDL_Color autosave_text_in_progress;
    SDL_Color autosave_text_success;
    SDL_Color autosave_text_failure;
    SDL_Color sync_heading;
    SDL_Color sync_idle;
    SDL_Color sync_pending;
    SDL_Color sync_success;
    SDL_Color sync_failure;
    SDL_Color sync_background;
    SDL_Color sync_border;
    SDL_Color achievements_heading;
    SDL_Color achievements_primary;
    SDL_Color achievements_secondary;
    SDL_Color achievements_background;
    SDL_Color achievements_border;
    SDL_Color performance_heading;
    SDL_Color performance_value;
    SDL_Color performance_warning;
    SDL_Color performance_background;
    SDL_Color performance_border;

    MainMenuPalette() noexcept;
};

MainMenuPalette::MainMenuPalette() noexcept
    : background()
    , title()
    , profile()
    , button_idle()
    , button_hover()
    , button_selected()
    , button_disabled()
    , button_disabled_hover()
    , button_border_enabled()
    , button_border_disabled()
    , button_text_enabled()
    , button_text_disabled()
    , description()
    , hint()
    , build()
    , alert_text_error()
    , alert_text_info()
    , alert_background_error()
    , alert_border_error()
    , alert_background_info()
    , alert_border_info()
    , overlay_heading()
    , overlay_line()
    , overlay_footer()
    , overlay_background()
    , overlay_border()
    , tutorial_title()
    , tutorial_primary()
    , tutorial_secondary()
    , tutorial_background()
    , tutorial_border()
    , autosave_icon_idle()
    , autosave_icon_in_progress()
    , autosave_icon_success()
    , autosave_icon_failure()
    , autosave_text_in_progress()
    , autosave_text_success()
    , autosave_text_failure()
    , sync_heading()
    , sync_idle()
    , sync_pending()
    , sync_success()
    , sync_failure()
    , sync_background()
    , sync_border()
    , achievements_heading()
    , achievements_primary()
    , achievements_secondary()
    , achievements_background()
    , achievements_border()
    , performance_heading()
    , performance_value()
    , performance_warning()
    , performance_background()
    , performance_border()
{
}
