#include "app_constants.hpp"
#include "backend_client.hpp"
#include "menu_localization.hpp"
#include "main_menu_system.hpp"
#include "game_bootstrap.hpp"
#include "save_system_background.hpp"
#include "player_profile.hpp"
#include "ui_input.hpp"
#include "ui_menu.hpp"

// Aggregated from refactored main menu modules
#include "main_menu_helpers.cpp"
#include "main_menu_alerts.cpp"
#include "main_menu_overlays.cpp"
#include "main_menu_event_loop.cpp"
#include "main_menu_actions.cpp"
