#include "save_system.hpp"
#include "libft/CMA/CMA.hpp"
#include "libft/CPP_class/class_nullptr.hpp"
#include "libft/Libft/limits.hpp"
#include "libft/Libft/libft.hpp"
#include "libft/Math/math.hpp"
#include "libft/Template/set.hpp"

// Aggregated from refactored save system modules
#include "save_system_scaling.cpp"
#include "save_system_planet_serialization.cpp"
#include "save_system_fleet_serialization.cpp"
#include "save_system_fleet_deserialization.cpp"
#include "save_system_research_and_achievements.cpp"
#include "save_system_buildings.cpp"
#include "save_system_building_preferences.cpp"
#include "save_system_campaign_progress.cpp"
