#include "game_test_control_manual_vs_auto.cpp"
#include "game_test_control_aggression.cpp"
#include "game_test_control_focus_fire.cpp"
#include "game_test_control_tactical_pause.cpp"
#include "game_test_control_sunflare.cpp"
