static bool run_main_post_campaign_verifications()
{
    if (!verify_building_tick_state_persistence())
        return false;

    if (!compare_energy_pressure_scenarios())
        return false;
    if (!verify_helios_beacon_energy_network())
        return false;
    if (!verify_crafting_resume_requires_full_cycle())
        return false;
    if (!compare_storyline_assaults())
        return false;
    if (!verify_emergency_energy_conservation())
        return false;
    if (!verify_narrative_assault_spikes())
        return false;
    if (!analyze_manual_vs_auto_assault_controls())
        return false;
    if (!measure_assault_aggression_effects())
        return false;
    if (!evaluate_focus_fire_cooldowns())
        return false;
    if (!validate_tactical_pause_behaviors())
        return false;
    if (!verify_ship_range_defaults())
        return false;
    if (!verify_design_doc_ship_roster())
        return false;
    if (!verify_range_aware_combat_power())
        return false;
    if (!verify_raider_ship_maneuver_profiles())
        return false;
    if (!verify_combat_tracker_deceleration())
        return false;
    if (!verify_raider_ships_unavailable_to_players())
        return false;
    if (!compare_generator_support())
        return false;
    if (!verify_auto_shield_generator_projection())
        return false;
    if (!inspect_support_ship_positioning())
        return false;
    if (!verify_sunflare_docking_focus())
        return false;
    if (!verify_sunflare_targeting_rules())
        return false;
    if (!verify_radar_static_defense_support())
        return false;
    if (!verify_auto_repair_drone_coordination())
        return false;
    if (!verify_difficulty_scaling())
        return false;
    if (!verify_crafting_and_energy_research())
        return false;
    if (!verify_auxiliary_and_escape_protocol())
        return false;
    if (!verify_save_system_round_trip())
        return false;
    if (!verify_save_system_edge_cases())
        return false;
    if (!verify_save_system_sanitizes_ship_movement_stats())
        return false;
    if (!verify_save_system_invalid_inputs())
        return false;
    if (!verify_save_system_rejects_oversized_building_grids())
        return false;
    if (!verify_save_system_prevents_building_instance_wraparound())
        return false;
    if (!verify_save_system_compact_building_serialization())
        return false;
    if (!verify_save_system_rejects_overlarge_ship_ids())
        return false;
    if (!verify_save_system_limits_inflated_ship_counts())
        return false;
    if (!verify_save_system_recovers_underreported_ship_counts())
        return false;
    if (!validate_save_system_serialized_samples())
        return false;
    if (!verify_save_system_allocation_failures())
        return false;
    if (!verify_save_system_extreme_scaling())
        return false;
    if (!verify_save_system_normalizes_non_finite_planet_values())
        return false;
    if (!verify_save_system_massive_payload())
        return false;
    if (!verify_save_system_sparse_entries())
        return false;
    if (!verify_save_system_recovers_corrupt_planet_snapshot())
        return false;
    if (!verify_save_system_sanitizes_corrupt_ship_stats())
        return false;
    if (!verify_planet_inventory_save_round_trip())
        return false;
    if (!verify_planet_inventory_resets_unsaved_items())
        return false;
    if (!verify_building_save_round_trip())
        return false;
    if (!verify_campaign_load_accepts_empty_building_payload())
        return false;
    if (!verify_research_save_round_trip())
        return false;
    if (!verify_achievement_save_round_trip())
        return false;
    if (!verify_campaign_checkpoint_flow())
        return false;
    if (!verify_campaign_rejects_invalid_save())
        return false;
    if (!verify_buildings_unchanged_on_failed_load())
        return false;
    if (!verify_new_game_save_name_rules())
        return false;
    if (!verify_new_game_save_creation())
        return false;
    if (!verify_new_game_save_launch_readiness())
        return false;
    if (!verify_tutorial_replay_save_creation())
        return false;
    if (!verify_player_profile_save())
        return false;
    if (!verify_save_system_prevents_ship_id_wraparound())
        return false;
    if (!verify_save_system_resolves_duplicate_ship_ids())
        return false;

    return true;
}
