#include "../libft/Libft/libft.hpp"
#include "../libft/System_utils/test_runner.hpp"
#include "../libft/Template/vector.hpp"
#include "../libft/Template/pair.hpp"
#include "fleets.hpp"
#include "research.hpp"
#include "quests.hpp"
#include "buildings.hpp"
#include "game_test_scenarios.hpp"

// Aggregated from refactored campaign test modules
#include "game_test_campaign_helpers.cpp"
#include "game_test_campaign_supply_routes.cpp"
#include "game_test_campaign_quests.cpp"
#include "game_test_campaign_combat.cpp"
#include "game_test_campaign_progression.cpp"
#include "game_test_campaign_branching.cpp"
#include "game_test_campaign_autosave.cpp"
#include "game_test_campaign_veterancy.cpp"
